[project]
name = "powertools-request-binding"
version = "0.1.0"
description = "An extension for AWS Lambda Powertools that provides model binding for request bodies, query parameters and path parameters."
authors = [
    {name = "Alejandro",email = "clandro89@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "aws-lambda-powertools (>=3.29.0,<4.0.0)",
    "modmex (>=1.1.3,<2.0.0)"
]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
